name: service-manager
services:
  - name: web
    git:
      repo: "https://github.com/jeqbrown/service-manager"
      branch: main
    build_command: pip install -r requirements.txt
    run_command: gunicorn service_manager.wsgi:application
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Build-time environment variables
    envs:
      - key: COLLECT_STATIC
        scope: BUILD_TIME
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        scope: BUILD_TIME
        value: "0"

      # Runtime environment variables
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_TIME
        value: "service_manager.platform_settings"
      - key: DIGITALOCEAN_APP_PLATFORM
        scope: RUN_TIME
        value: "True"
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${DJANGO_SECRET_KEY}
      - key: ALLOWED_HOST
        scope: RUN_TIME
        value: "svcflo.com,stingray-app-rjzyb.ondigitalocean.app"

      # Database connection (using bindable variables)
      - key: POSTGRES_DB
        scope: RUN_TIME
        value: ${db.DATABASE}
      - key: POSTGRES_USER
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ${db.PASSWORD}
      - key: POSTGRES_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      - key: POSTGRES_PORT
        scope: RUN_TIME
        value: ${db.PORT}

    # HTTP port configuration
    http_port: 8000
    
    # Health check configuration
    health_check:
      http_path: /health/
      initial_delay_seconds: 30
      period_seconds: 60

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: service-manager-db
    version: "14"

static_sites:
  - name: static
    git:
      repo: "https://github.com/jeqbrown/service-manager"
      branch: main
    build_command: python manage.py collectstatic --noinput
    output_dir: staticfiles
    routes:
      - path: /static
