name: service-manager
services:
  - name: web
    source_dir: Service_Manager
    github:
      branch: main
      repo: jeqbrown/service-manager
    build_command: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    run_command: gunicorn service_manager.wsgi:application --bind=0.0.0.0:8000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_TIME
        value: service_manager.platform_settings
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${DJANGO_SECRET_KEY}
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: ".ondigitalocean.app"
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

databases:
  - engine: PG
    name: db
    version: "14"

static_sites:
  - name: static
    source_dir: Service_Manager
    github:
      branch: main
      repo: jeqbrown/service-manager
    build_command: python manage.py collectstatic --noinput
    output_dir: staticfiles
    routes:
      - path: /static
