name: service-manager
services:
  - name: web
    git:
      repo: "https://github.com/jeqbrown/service-manager"
      branch: main
    build_command: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    run_command: gunicorn service_manager.wsgi:application --bind=0.0.0.0:8000
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Build-time environment variables
    envs:
      - key: COLLECT_STATIC
        scope: BUILD_TIME
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        scope: BUILD_TIME
        value: "0"
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_TIME
        value: "service_manager.platform_settings"
      - key: DIGITALOCEAN_APP_PLATFORM
        scope: RUN_TIME
        value: "True"
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${DJANGO_SECRET_KEY}
      - key: ALLOWED_HOST
        scope: RUN_TIME
        value: "${APP_DOMAIN},${PUBLIC_URL}"

    # Database configuration
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      
    http_port: 8000
    
    health_check:
      http_path: /health/
      initial_delay_seconds: 30
      period_seconds: 60
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

databases:
  - engine: PG
    name: db
    version: "14"

static_sites:
  - name: static
    git:
      repo: "https://github.com/jeqbrown/service-manager"
      branch: main
    build_command: python manage.py collectstatic --noinput
    output_dir: staticfiles
    routes:
      - path: /static
