# Generated by Django 5.1.5 on 2025-02-27 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', 'new_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-is_primary', 'name']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='primary_contact',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='service.instrumenttype'),
        ),
    ]
