# Generated by Django 5.1.5 on 2025-02-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_add_assigned_work_order_to_entitlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='service.entitlement'),
        ),
    ]
