# Generated by Django 5.1.5 on 2025-03-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_entitlement_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-due_date']},
        ),
        migrations.RenameField(
            model_name='servicereport',
            old_name='actions_taken',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='entitlement',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='instrument',
        ),
        # Remove duplicate timestamp fields since they were added in migration 0003
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='service.instrument'),
        ),
        migrations.AlterField(
            model_name='entitlementtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
