# Generated by Django 5.1.5 on 2025-02-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_entitlement_assigned_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='service.workorder'),
        ),
    ]
