# Generated by Django 5.1.5 on 2025-03-13 01:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_workorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='total_visits',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='used_visits',
        ),
        migrations.RemoveField(
            model_name='entitlementtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entitlementtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entitlementtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entitlementtype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='serviceagreement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceagreement',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='created_by',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='total',
            field=models.PositiveIntegerField(default=1, help_text='Total number of visits/services allowed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='service_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
