# Generated by Django 5.1.6 on 2025-02-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_update_entitlement_model'),
        ('service', '0006_workorder_assigned_to_alter_workorder_created_by'),
    ]

    operations = [
    ]
