# Generated by Django 5.1.6 on 2025-02-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_merge_20250214_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='service.instrument'),
        ),
    ]
