# Generated by Django 5.1.6 on 2025-02-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_rename_entitlement_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='servicereport',
            options={'ordering': ['-service_date']},
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='customer',
        ),
        migrations.AddField(
            model_name='servicereport',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
