# Generated by Django 5.1.6 on 2025-02-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_customer_options_alter_servicereport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='service.instrument'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='total',
            field=models.PositiveIntegerField(help_text='Total number of visits/services allowed'),
        ),
    ]
