# Generated by Django 5.1.5 on 2025-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_workorder_servicereport_relationship_improvements'),
        ('service', '0017_add_po_number_to_agreement'),
    ]

    operations = [
    ]
